apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-secret
data:
  MONGO_URI: {{ .Values.mongodb.uri | b64enc }}
  STATIC_TOKEN: {{ .Values.api.staticToken | b64enc }}
  ACTS_GEN_USER: {{ .Values.api.actsGenUser | b64enc }}
  ACTS_GEN_PASSWORD: {{ .Values.api.actsGenPassword | b64enc }}
